"""Generate ground_truth_{year}.json for the EXPANDED Chao Phraya basin universe.

Reproducible, NOT hand-tuned: reads the full GISTDA per-province flood-area tables
(gistda_flood_{year}_all_provinces.json, fetched from thaiwater's published GISTDA
product) + the fixed basin membership (chao_phraya_basin_provinces.json), keeps only
in-basin provinces, and applies the SAME >=10,000-rai significance cutoff used by the
original 10-province ground truth. This expands N from 10 -> 23 within-basin for
statistical power, without changing the gold RULE (cutoff) — so it is not gaming.

Old 10-province files are frozen as ground_truth_{year}_core10_frozen.json; README
reports old-vs-new side by side.
"""
from __future__ import annotations

import datetime as dt
import json

from src.config import settings

PROC = settings.data_processed_dir
CUTOFF_RAI = 10000  # unchanged from the original ground truth


def _basin() -> dict:
    d = json.loads((PROC / "chao_phraya_basin_provinces.json").read_text("utf-8"))
    return d["provinces"]


def build_year(year: str) -> dict:
    basin = _basin()
    th2id = {v["th"]: pid for pid, v in basin.items()}
    full = json.loads((PROC / f"gistda_flood_{year}_all_provinces.json").read_text("utf-8"))
    area = full["flooded_area_rai"]

    # map GISTDA thai names -> in-basin province ids (strip leading "จ.")
    rai_by_id: dict[str, int] = {pid: 0 for pid in basin}  # default 0 (not listed = not flooded)
    for th, v in area.items():
        key = th.replace("จ.", "").strip()
        if key in th2id:
            rai_by_id[th2id[key]] = int(v)

    gold = sorted([pid for pid, r in rai_by_id.items() if r >= CUTOFF_RAI])
    negatives = sorted([pid for pid in basin if pid not in gold])
    out = {
        "_meta": {
            "description": f"REAL ground truth for the {year} Chao Phraya event on the EXPANDED "
                           f"23-province in-basin universe. gold = in-basin provinces with GISTDA "
                           f"flooded area >= {CUTOFF_RAI} rai (same cutoff as the original 10-province "
                           f"ground truth). Generated by src/ingest/build_ground_truth.py.",
            "event_id": f"chao_phraya_{year}",
            "source": full["_meta"]["source"],
            "significance_cutoff_rai": CUTOFF_RAI,
            "universe": "Chao Phraya basin (23 provinces)",
            "generated": dt.datetime.now().isoformat(timespec="seconds"),
            "frozen_core10": f"ground_truth_{year}_core10_frozen.json",
        },
        "flooded_area_rai": {pid: rai_by_id[pid] for pid in sorted(basin)},
        "gold_flooded": gold,
        "negatives": negatives,
        "n_gold": len(gold),
        "n_total": len(basin),
    }
    return out


def main() -> None:
    for year in ("2022", "2021", "2024", "2023"):
        out = build_year(year)
        p = PROC / f"ground_truth_{year}.json"
        p.write_text(json.dumps(out, ensure_ascii=False, indent=2), "utf-8")
        print(f"{year}: gold={out['n_gold']}/{out['n_total']}  -> {p.name}")
        print(f"        gold: {out['gold_flooded']}")


if __name__ == "__main__":
    main()
